name: Upload & Deploy App

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    container:
      image: ghcr.io/mitchell-lemons-invs/wdcli-runner:1.8.25
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Dump WDCLI Version
        run: wdcli version

      - name: Export Environment Variables
        run: |
          echo "WDCLI_CLIENT_ID=${{ vars.SystemUserClientId }}" >> $GITHUB_ENV
          echo "WDCLI_CLIENT_SECRET=${{ secrets.SystemUserClientSecret }}" >> $GITHUB_ENV

      - name: Authenticate
        run: wdcli auth login --system-user

      - name: Ensure Correct Account
        run: wdcli account switch ${{ vars.AccountShortId }} --ci -f json

      - name: Upload application
        run: wdcli app upload app/ -f json

      - name: Login to tenant
        run: wdcli tenant login ${{ vars.WcpDevTenantAlias }} --ci