name: Manual Workflow

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: extract wdcli
        run: tar xzvf bin/wdcli-installer-linux-x64-v1.8.25.tar.gz -C bin/

      - name: Dump Version
        run: bin/wdcli/bin/wdcli version

      - name: Export Environment Variables
        env:
          WDCLI_CLIENT_ID: ${{ vars.SystemUserClientId }}
          WDCLI_CLIENT_SECRET: ${{ secrets.SystemUserClientSecret }}

      - name: Authenticate
        run: bin/wdcli/bin/wdcli auth login --system-user